import React from 'react';

const MLPredictionViewer = ({ loading, error, predictionData, onNavigate }) => {
  if (loading) {
    return (
      <div className="loading-container">
        <div className="spinner"></div>
        <p className="loading-text">Fetching ML prediction...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="error-message-box">
        <p className="error-title">Error!</p>
        <p className="error-text">{error}</p>
        <p className="error-hint">Please ensure your Python ML backend is running and accessible.</p>
        <button className="home-button mt-4" onClick={() => onNavigate('home')}>
          Back to Home
        </button>
      </div>
    );
  }

  return (
    <div className="ml-prediction-section">
      <h2 className="sdoml-title">Solar Flare Peak Time Prediction</h2>
      <p className="sdoml-intro">
        This section displays the predicted peak offset time for solar flares.
        The prediction is generated by a trained LSTM model running on a Python backend.
      </p>

      {predictionData ? (
        <div className="prediction-results">
          <h3>Prediction Details:</h3>
          <p><strong>Predicted Offset (seconds):</strong> {predictionData.prediction.toFixed(2)}</p>
          <p>This is the model's primary prediction. It means the solar flare is predicted to reach its peak intensity approximately {predictionData.prediction.toFixed(2)} seconds after its observed start time.</p>
          <p><strong>Predicted Offset (HH:MM:SS):</strong> {predictionData.prediction_formatted_offset}</p>
          <p>This is the same "peak offset" but presented in a more human-readable hours:minutes:seconds format. It tells you the peak is expected {predictionData.prediction_formatted_offset} after the flare begins.</p>
          <p><strong>Predicted Absolute Peak Time:</strong> {predictionData.predicted_peak_time}</p>
          <p>This is the most actionable piece of information for a specific flare. If the flare started at a particular time, and the model predicts a peak offset of {predictionData.prediction_formatted_offset}, then the absolute time when the flare is expected to reach its peak intensity is {predictionData.predicted_peak_time} hours.</p>
          <p><strong>Timestamp:</strong> {new Date(predictionData.timestamp).toLocaleString()}</p>
        </div>
      ) : (
        <p className="text-gray-400 mt-4">
          No prediction data available. Please ensure the ML backend is correctly configured and the prediction request succeeded.
        </p>
      )}

      <div className="button-group mt-8">
        <button className="home-button" onClick={() => onNavigate('home')}>
          Back to Home
        </button>
        
        <button className="home-button ml-4" onClick={() => onNavigate('ml-graphs')}>
          View Model Graphs
        </button>
      </div>
    </div>
  );
};

export default MLPredictionViewer;
